// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtAwp4hRBu_2OvDGvF_nWENvwNAw88guQ',
    appId: '1:269736211423:web:c722452d825bb860b48a6a',
    messagingSenderId: '269736211423',
    projectId: 'foodie-1db05',
    authDomain: 'foodie-1db05.firebaseapp.com',
    storageBucket: 'foodie-1db05.appspot.com',
    measurementId: 'G-NE716DTJ56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk1qzDTbsi5HqpzcGjtxpngTmQBC5kLus',
    appId: '1:269736211423:android:8cdf027dd02729d4b48a6a',
    messagingSenderId: '269736211423',
    projectId: 'foodie-1db05',
    storageBucket: 'foodie-1db05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZXXoB7dXKoTvdqnqplaETotHCZ8gAzk4',
    appId: '1:269736211423:ios:00d2762131cc24f7b48a6a',
    messagingSenderId: '269736211423',
    projectId: 'foodie-1db05',
    storageBucket: 'foodie-1db05.appspot.com',
    iosBundleId: 'com.example.shawky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZXXoB7dXKoTvdqnqplaETotHCZ8gAzk4',
    appId: '1:269736211423:ios:00d2762131cc24f7b48a6a',
    messagingSenderId: '269736211423',
    projectId: 'foodie-1db05',
    storageBucket: 'foodie-1db05.appspot.com',
    iosBundleId: 'com.example.shawky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtAwp4hRBu_2OvDGvF_nWENvwNAw88guQ',
    appId: '1:269736211423:web:7a3e3093fc1a4e69b48a6a',
    messagingSenderId: '269736211423',
    projectId: 'foodie-1db05',
    authDomain: 'foodie-1db05.firebaseapp.com',
    storageBucket: 'foodie-1db05.appspot.com',
    measurementId: 'G-8FDRQGJ58E',
  );
}
